### ISSUE TITLE
Adding Header To Publisher

### ISSUE THREAD

**Issue by ardaorkin** [Surnet/graphql-amqp-subscriptions#26]
Hello. In the [amqplib](https://www.npmjs.com/package/amqplib) library, we can add **headers** object to publisher properties.
I use [tortoise](https://www.npmjs.com/package/tortoise) in other services and I can add header to the publisher like that:
```javascript
var Tortoise = require("tortoise"),
  tortoise = new Tortoise(
    "amqp://localhost"
  );

tortoise
  .exchange("my-exchange", "direct", { durable: false })
  .publish(
    "routing.key",
    { Hello: "world" },
    { headers: { auth: "example_header" } }
  );
```

And I can take the header via consumer like that:

```javascript
var Tortoise = require("tortoise"),
  tortoise = new Tortoise(
    "amqp:/localhost"
  );
tortoise
  .queue("my-queue", { durable: false })
  .exchange("my-exchange", "direct", "routing.key", { durable: false })
  .prefetch(1)
  .subscribe(function (msg, ack, nack) {
    console.log(this);
    ack(); 
  });

```
This code logs to the console this:
```javascript
{
  fields: {
    consumerTag: 'amq.ctag--5T19DPGYqJzwCBZ4xlsqg',
    deliveryTag: 1,
    redelivered: false,
    exchange: 'my-exchange',
    routingKey: 'routing.key'
  },
  properties: {
    contentType: undefined,
    contentEncoding: undefined,
    headers: { auth: 'example_header' },
    deliveryMode: undefined,
    priority: undefined,
    correlationId: undefined,
    replyTo: undefined,
    expiration: undefined,
    messageId: undefined,
    timestamp: undefined,
    type: undefined,
    userId: undefined,
    appId: undefined,
    clusterId: undefined
  },
  content: <Buffer 7b 7d>
}
```

I tried to add a header to the publisher which is reproduced from AQMPPubSub like below, but it doesn't work:
```
pubsub.publish("routing.key", {Hello: "world"} , {
      headers: { auth: "example_header" },
    });
```

Is there a way to add a header to the publisher reproduced from AMQPPubSub?

**Comment by chdanielmueller** [comment]
I'll take a look at it

**Comment by chdanielmueller** [comment]
@ardaorkin Please try to install the version from the branch with this command:
`npm install github:Surnet/graphql-amqp-subscriptions#add-options-to-pubsub --save`
It should work as you would expect it to

**Comment by ardaorkin** [comment]
Hi @chdanielmueller 
Thank you for the reply.
I tried your suggestion. Unfortunately, I've got an error when I ran the project:
```javascript
internal/modules/cjs/loader.js:311
      throw err;
      ^

Error: Cannot find module 'C:\Users\ArdaÖrkin\Projects\screen-machine\node_modules\graphql-amqp-subscriptions\lib\index.js'. Please verify that the package.json has a valid "main" entry
    at tryPackage (internal/modules/cjs/loader.js:303:19)
    at Function.Module._findPath (internal/modules/cjs/loader.js:516:18)
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:867:27)
    at Function.Module._load (internal/modules/cjs/loader.js:725:27)
    at Module.require (internal/modules/cjs/loader.js:952:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at Object.<anonymous> (C:\Users\ArdaÖrkin\Projects\screen-machine\amqp\/amqpPubSub.js:1:1)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Module._compile (C:\Users\ArdaÖrkin\Projects\screen-machine\node_modules\pirates\lib\index.js:99:24)
    at Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Object.newLoader [as .js] (C:\Users\ArdaÖrkin\Projects\screen-machine\node_modules\pirates\lib\index.js:104:7)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Module.require (internal/modules/cjs/loader.js:952:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at Object.<anonymous> (C:\Users\ArdaÖrkin\Projects\screen-machine\/server.js:8:1) {
  code: 'MODULE_NOT_FOUND',
  path: 'C:\\Users\\ArdaÖrkin\\Projects\\screen-machine\\node_modules\\graphql-amqp-subscriptions\\package.json',
  requestPath: 'graphql-amqp-subscriptions'
}
[nodemon] app crashed - waiting for file changes before starting...

```

What should I suppose to do?

**Comment by chdanielmueller** [comment]
ohh of course...
It needs to be built first and the built files need to be in node_modules
You can reinstall the working version and then replace the lib folder in node_modules/graphql-amqp-subscriptions
That should work

[lib.zip](https://github.com/Surnet/graphql-amqp-subscriptions/files/6434535/lib.zip)

**Comment by ardaorkin** [comment]
It works! Wonderful!! Thank you so much!
Will you create a new version with this feature? So I can use this feature in another project without the need to copy and paste the **lib** folder each time.

**Comment by chdanielmueller** [comment]
Sure. I will deploy this version soon.
Just wanted to make sure it works as expected.

Could you please test the subscription with different headers?
I am not 100% sure it works as expected then.
The publish should not be an issue.
But as far as I can tell it will only use the first subscriptions headers and the second one will be assigned to the same subscription.

**Comment by ardaorkin** [comment]
Sure, I'll test with different headers. I'll let you know.

**Comment by chdanielmueller** [comment]
Thanks, I will wait for your feedback before I release the version. 😄

**Comment by ardaorkin** [comment]
I made tests.
In my use case, I take the authorization header, which is ended by the client in the request body, and use this authorization header in mutation resolvers. Every mutation resolver publishes a message to RabbitMQ when they are triggered. Just for test cases, I wrote routing keys to the publishers' headers property like that:
```javascript
pubsub.publish(
          "ALL_USERS_REQUESTED",
          {},
          {
            contentType: "file",
            headers: { auth: "ALL_USERS_REQUESTED" },
          }
        )
pubsub.publish("CREATE_USER_REQUEST", 
        user, 
        {
          contentType: "file",
          headers: { auth: "CREATE_USER_REQUEST" },
        })
pubsub.publish(
          "UPDATE_USER_REQUEST",
          { id, body },
          {
            contentType: "file",
            headers: { auth: "UPDATE_USER_REQUEST" },
          }
        )
pubsub.publish("DELETE_USER_REQUEST", 
       userID, 
       {
          contentType: "file",
          headers: { auth: "DELETE_USER_REQUEST" },
        })
```

And when messages came to the consumer, I logged the messages info to the console and I can see that the feature is working as I expected:
```javascript
{
  fields: {
    consumerTag: 'amq.ctag-fj0IFkL6SfPPQDJPPGxtLw',
    deliveryTag: 8,
    redelivered: false,
    exchange: 'screen-machine',
    routingKey: 'ALL_USERS_REQUESTED'
  },
  properties: {
    contentType: 'file',
    contentEncoding: undefined,
    headers: { auth: 'ALL_USERS_REQUESTED' }, 
    deliveryMode: undefined,
    priority: undefined,
    correlationId: undefined,
    replyTo: undefined,
    expiration: undefined,
    messageId: undefined,
    timestamp: undefined,
    type: undefined,
    userId: undefined,
    appId: undefined,
    clusterId: undefined
  },
  content: <Buffer 7b 7d>
}

{
  fields: {
    consumerTag: 'amq.ctag-fj0IFkL6SfPPQDJPPGxtLw',
    deliveryTag: 9,
    redelivered: false,
    exchange: 'screen-machine',
    routingKey: 'UPDATE_USER_REQUEST'
  },
  properties: {
    contentType: 'file',
    contentEncoding: undefined,
    headers: { auth: 'UPDATE_USER_REQUEST' }, 
    deliveryMode: undefined,
    priority: undefined,
    correlationId: undefined,
    replyTo: undefined,
    expiration: undefined,
    messageId: undefined,
    timestamp: undefined,
    type: undefined,
    userId: undefined,
    appId: undefined,
    clusterId: undefined
  },
  content: <Buffer 7b 22 69 64 22 3a 22 36 30 
39 33 64 64 36 61 31 63 38 38 32 31 32 65 31 34 37 62 33 39 32 63 22 2c 22 62 6f 64 79 22 3a 7b 22 66 69 72 73 74 5f 6e 61 ... 19 more bytes>
}

{
  fields: {
    consumerTag: 'amq.ctag-fj0IFkL6SfPPQDJPPGxtLw',
    deliveryTag: 10,
    redelivered: false,
    exchange: 'screen-machine',
    routingKey: 'DELETE_USER_REQUEST'
  },
  properties: {
    contentType: 'file',
    contentEncoding: undefined,
    headers: { auth: 'DELETE_USER_REQUEST' }, 
    deliveryMode: undefined,
    priority: undefined,
    correlationId: undefined,
    replyTo: undefined,
    expiration: undefined,
    messageId: undefined,
    timestamp: undefined,
    type: undefined,
    userId: undefined,
    appId: undefined,
    clusterId: undefined
  },
  content: <Buffer 22 36 30 39 33 64 64 36 61 
31 63 38 38 32 31 32 65 31 34 37 62 33 39 32 63 22>
}
```

Should I use further tests? If I should, what kind of scenarios I better test?

**Comment by ardaorkin** [comment]
Hello @chdanielmueller. Is there any progress on testing changes and reproducing a new version?

**Comment by chdanielmueller** [comment]
@ardaorkin 
I plan to add your tests as tests in the repository and publish the new version afterwards.
I think I should be able to do it on monday.
Sorry for taking so long

**Comment by ardaorkin** [comment]
Thank you very much @chdanielmueller 
Best regards.

**Comment by chdanielmueller** [comment]
Version 1.2.0 is published.
I incorporated your test as a CI test in the package.
Thank you for your testing!

I also added some more functionality for the subscribe and publish portion which would allow to extend this package for header exchanges if this becomes a feature request in the future.

**Comment by ardaorkin** [comment]
Thank you very much @chdanielmueller !
Great news!
